# Generated by Django 5.1.1 on 2024-10-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base', models.CharField(blank=True, max_length=100, null=True)),
                ('principal', models.CharField(blank=True, max_length=100, null=True)),
                ('constructor_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('FP1', 'Free Practice 1'), ('FP2', 'Free Practice 2'), ('FP3', 'Free Practice 3'), ('Q', 'Qualifying'), ('R', 'Race')], max_length=3)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('grand_prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.grandprix')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('session_type', 'grand_prix')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField()),
                ('distance', models.FloatField(help_text='Distance covered in meters')),
                ('speed', models.FloatField(help_text='Speed in km/h')),
                ('throttle', models.FloatField(help_text='Throttle percentage')),
                ('brake', models.FloatField(help_text='Brake percentage')),
                ('gear', models.IntegerField(help_text='Current gear')),
                ('rpm', models.IntegerField(help_text='Engine RPM')),
                ('drs', models.BooleanField(help_text='DRS active status')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries', to='api.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries', to='api.session')),
            ],
            options={
                'ordering': ['session', 'driver', 'lap', 'distance'],
                'unique_together': {('session', 'driver', 'lap', 'distance')},
            },
        ),
    ]
